# A workflow to update the IDs of the systems
name: dummy_test

# Controls when the workflow will run
on:   
  pull_request:
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "GenerateIDs"
  stupidWork:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Assign new IDs
        id: newids
        run: |
          echo "Currently working in:"
          pwd
          cd $GITHUB_WORKSPACE/Data/Simulations
          touch babaBIBI.txt

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          commit-message: Update simulation IDs
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: workflow_addID_PR
          branch-suffix: short-commit-hash
          title: Update IDs after pull request ${{ github.event.number}}
          body: |
            Generated new IDs for duplicates or new systems in #${{ github.event.number}}.
            Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            UpdateID
            AutoPR
          draft: false
